"""Google ADK-backed Collaborative Partner with a deterministic local demo mode."""
from __future__ import annotations

import os
import uuid
from dataclasses import asdict, dataclass

from .memory import TeamMemory, TermRecord


@dataclass
class Explanation:
    definition: str
    why_it_matters: str
    next_action: str
    source: str
    clarification: str | None = None


class TeamUnjargonPartner:
    def __init__(self, memory: TeamMemory) -> None:
        self.memory = memory
        self.demo_mode = os.getenv("TEAM_UNJARGON_DEMO_MODE", "true").lower() == "true"
        self.model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    async def explain(self, team_id: str, member: str, term: str, context: str) -> Explanation:
        record = self.memory.get_term(team_id, term)
        if self.demo_mode:
            return self._demo_explanation(term, record)
        return await self._adk_explanation(term, context, record)

    def _demo_explanation(self, term: str, record: TermRecord | None) -> Explanation:
        if record:
            return Explanation(
                definition=record.definition,
                why_it_matters=record.team_context,
                next_action="Use this team-approved wording in your next agent prompt or review.",
                source="team memory",
            )
        return Explanation(
            definition=f"{term} is not yet defined by this team.",
            why_it_matters="The team should establish a shared meaning before relying on it in an agent workflow.",
            next_action="Ask one teammate for the intended meaning, then save a concise correction.",
            source="tentative demo explanation",
            clarification=f"Which project or workflow is {term} referring to?",
        )

    async def _adk_explanation(self, term: str, context: str, record: TermRecord | None) -> Explanation:
        """Run the same prompt through Google ADK when deployed with Vertex/Gemini credentials."""
        try:
            from google.adk.agents import LlmAgent
            from google.adk.runners import Runner
            from google.adk.sessions import InMemorySessionService
            from google.genai import types
        except ImportError as error:  # pragma: no cover - deployment dependency
            raise RuntimeError("Google ADK is unavailable. Install requirements and configure Gemini credentials.") from error

        memory_text = "No team-approved definition exists." if not record else (
            f"Approved definition: {record.definition}\nTeam context: {record.team_context}\n"
            f"Helpful confirmations: {record.helpful_count}"
        )
        instruction = (
            "You are Team unjargon, a Collaborative Partner for an AI-native team. "
            "Explain one term in plain language. Never ask for or infer a full transcript. "
            "Return exactly three short labeled lines: Definition:, Why it matters:, Next action:. "
            "If the term is ambiguous, add one Clarification: line.\n\n"
            f"Team memory:\n{memory_text}"
        )
        agent = LlmAgent(name="team_unjargon_partner", model=self.model, instruction=instruction)
        sessions = InMemorySessionService()
        runner = Runner(agent=agent, app_name="team_unjargon", session_service=sessions)
        user_id, session_id = "web-member", str(uuid.uuid4())
        await sessions.create_session(app_name="team_unjargon", user_id=user_id, session_id=session_id)
        prompt = f"Term: {term}\nOptional member context: {context or '(none)'}"
        answer = ""
        try:
            async for event in runner.run_async(
                user_id=user_id,
                session_id=session_id,
                new_message=types.Content(role="user", parts=[types.Part(text=prompt)]),
            ):
                if event.is_final_response() and event.content and event.content.parts:
                    answer = "".join(part.text or "" for part in event.content.parts)
        except Exception as error:  # Vertex errors are retryable deployment configuration errors.
            raise RuntimeError(f"Gemini is temporarily unavailable: {error}") from error
        if not answer:
            raise RuntimeError("Gemini returned no final response.")
        fields = {"Definition": "", "Why it matters": "", "Next action": "", "Clarification": None}
        for line in answer.splitlines():
            for label in fields:
                prefix = f"{label}:"
                if line.startswith(prefix):
                    fields[label] = line[len(prefix):].strip()
        return Explanation(
            definition=fields["Definition"] or answer,
            why_it_matters=fields["Why it matters"] or "Generated by Gemini for this team.",
            next_action=fields["Next action"] or "Confirm the meaning with your team.",
            clarification=fields["Clarification"],
            source="Gemini + ADK" if not record else "team memory + Gemini + ADK",
        )
